apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
  - port: 80
    targetPort: 8080
